//
// Created by hodaya on 11/23/18.
//

#ifndef EXCELLENTEAM_ELLA_CPP_MEMORY_ALLOCATOR_HODAYAMAR_MEMORY_ALLOCATION_SERVICE_H
#define EXCELLENTEAM_ELLA_CPP_MEMORY_ALLOCATOR_HODAYAMAR_MEMORY_ALLOCATION_SERVICE_H

#endif //EXCELLENTEAM_ELLA_CPP_MEMORY_ALLOCATOR_HODAYAMAR_MEMORY_ALLOCATION_SERVICE_H
